GET http://localhost:3000/status_catalog
###

GET http://localhost:3000/status_catalog?limit=2
###

GET http://localhost:3000/status_catalog/13
###

POST http://localhost:3000/status_catalog/create
Content-Type: application/json

{
   "name": "Onin"
}
###

PUT http://localhost:3000/status_catalog/1
Content-Type: application/json

{
   "name": "Janick"
}
###

DELETE http://localhost:3000/status_catalog/1