GET http://localhost:3000/status_catalog
###

GET http://localhost:3000/status_catalog?limit=2
###

GET http://localhost:3000/status_catalog/13
###

POST http://localhost:3000/status_catalog/create
Content-Type: application/json

{
  "name": "Sample Name",
  "code": "Sample Code",
  "city": "Sample City"
}
###

PUT http://localhost:3000/status_catalog/1
Content-Type: application/json

{
  "name": "Updated Name",
  "code": "Updated Code",
  "city": "Updated City"
}
###

DELETE http://localhost:3000/status_catalog/12