GET http://localhost:3000/driver
###

GET http://localhost:3000/driver?limit=2
###

GET http://localhost:3000/driver/13
###

POST http://localhost:3000/driver/create
Content-Type: application/json

{
  "car_make": "Ferrari",
    "car_model": "F-150",
    "car_year": 68,
    "user_id": 4,
    "online": true,
    "delivering": true
}
###

PUT http://localhost:3000/driver/4
Content-Type: application/json

{
    "car_make": "lambo",
    "car_model": "F-150",
    "car_year": 68,
    "user_id": 10,
    "online": true,
    "delivering": true
}
###

DELETE http://localhost:3000/driver/12