GET http://localhost:3000/states
###
GET http://localhost:3000/states?limit=2
###
GET http://localhost:3000/states/2000


###
POST http://localhost:3000/states/create
Content-Type: application/json

{
       "name": "bang",
    "code": "dfsdf"

}

###
PUT http://localhost:3000/states/1
Content-Type: application/json

{
        "name": "bluuuueeeeee",
    "code": "dfsdf"

}

###
DELETE http://localhost:3000/states/6
