GET http://localhost:3000/city
###

GET http://localhost:3000/city?limit=2
###

GET http://localhost:3000/city/13
###

POST http://localhost:3000/city/create
Content-Type: application/json

{
   "name": "house",
  "state_id": 1
}
###

PUT http://localhost:3000/city/1
Content-Type: application/json

{
   "name": "higkjk",
  "state_id": 2
}
###

DELETE http://localhost:3000/city/12