GET http://localhost:3000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI0LCJyb2xlIjoidXNlciIsImV4cCI6MTcxODQ0MTIwMH0.ULfynVV2JpEnZTfxt3-GV_78VsQkN7_qGo7efvyzks0
###
GET http://localhost:3000/api/users?limit=2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODExMjc4Nn0.mjlq0BvWup5ovtFemSqKPsWh3Q2XYzaUu_48D2UZLpo
###

GET http://localhost:3000/api/users/14
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODExMjc4Nn0.mjlq0BvWup5ovtFemSqKPsWh3Q2XYzaUu_48D2UZLpo
###

POST http://localhost:3000/api/users/create
Content-Type: application/json

{
    "name": "mugambe",
    "contact_phone": "09383",
    "phone_verified": true,
    "email": "Kenna39@hotmail.com",
    "email_verified": true,
    "confirmation_code": "zQg4P4",
    "password": "Ysi8sxDxOI9tu1v"
}
###
PUT http://localhost:3000/api/users/14
Content-Type: application/json

{
    "name": "kindly",
    "contact_phone": "09383",
    "phone_verified": true,
    "email": "Kenna39@hotmail.com",
    "email_verified": true,
    "confirmation_code": "zQg4P4"
}
###
DELETE http://localhost:3000/users/15
