GET http://localhost:3000/restaurant
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODI2MTEzNn0.Sa6SjTElND47KQnssSYMjEyEFDX-LzVwGJEtbzH_OFY
###

GET http://localhost:3000/restaurant?limit=2
###

GET http://localhost:3000/restaurant/13
###

POST http://localhost:3000/restaurant/create
Content-Type: application/json

{
   "name": "bricks-and-suu",
    "street_address": "659 Lincoln Highway",
    "zip_code": "24349-7015",
    "city_id": 10
}
###

PUT http://localhost:3000/restaurant/1
Content-Type: application/json

{ 
  "name": "bricks-and-clicks",
    "street_address": "659 Lincoln Highway",
    "zip_code": "24349-7015",
    "city_id": 10
}
###

DELETE http://localhost:3000/restaurant/12