GET http://localhost:3000/category
###

GET http://localhost:3000/category?limit=2
###

GET http://localhost:3000/category/13
###

POST http://localhost:3000/category/create
Content-Type: application/json

{
  "name": "Sample Name",
  "code": "Sample Code",
  "city": "Sample City"
}
###

PUT http://localhost:3000/category/1
Content-Type: application/json

{
  "name": "Updated Name",
  "code": "Updated Code",
  "city": "Updated City"
}
###

DELETE http://localhost:3000/category/12