GET http://localhost:3000/order_status
###

GET http://localhost:3000/order_status?limit=2
###

GET http://localhost:3000/order_status/13
###

POST http://localhost:3000/order_status/create
Content-Type: application/json

{
   "order_id": 22,
    "status_catalog_id": 5
}
###

PUT http://localhost:3000/order_status/1
Content-Type: application/json

{
   "order_id": 37,
    "status_catalog_id": 5
}
###

DELETE http://localhost:3000/order_status/12