GET http://localhost:3000/menu_item
###

GET http://localhost:3000/menu_item?limit=2
###

GET http://localhost:3000/menu_item/13
###

POST http://localhost:3000/menu_item/create
Content-Type: application/json

{
  "name": "nomee",
    "restaurant_id": 9,
    "category_id": 8,
    "description": "Thymbra adeo cariosus volaticus venustas suffoco pecus tenax territo.",
    "ingredients": "Versus versus terga ciminatio vorax.",
    "price": 808.00,
    "active": false
}
###

PUT http://localhost:3000/menu_item/11
Content-Type: application/json

{
 "name": "Towels",
    "restaurant_id": 9,
    "category_id": 8,
    "description": "Thymbra adeo cariosus volaticus venustas suffoco pecus tenax territo.",
    "ingredients": "Versus versus terga ciminatio vorax.",
    "price": 808.00,
    "active": false
}
###

DELETE http://localhost:3000/menu_item/12