GET http://localhost:3000/address
###

GET http://localhost:3000/address?limit=2
###

GET http://localhost:3000/address/13
###

POST http://localhost:3000/address/create
Content-Type: application/json

{
    "street_address_1": "huuu",
    "street_address_2": "sadasdsadas",
    "zip_code": "2323",
    "delivery_instructions": "sdsfsdgdfg",
    "user_id": 2,
    "city_id": 1
}
###

PUT http://localhost:3000/address/14
Content-Type: application/json

{
    "street_address_1": "mwaaa",
    "street_address_2": "sadasdsadas",
    "zip_code": "2323",
    "delivery_instructions": "sdsfsdgdfg",
    "user_id": 2,
    "city_id": 1
}
###

DELETE http://localhost:3000/address/12