GET http://localhost:3000/orders
###

GET http://localhost:3000/orders?limit=2
###

GET http://localhost:3000/orders/13
###

POST http://localhost:3000/orders/create
Content-Type: application/json

{
    "restaurant_id": 19,
    "delivery_address_id": 21,
    "user_id": 8,
    "driver_id": 5,
    "price": 873.00,
    "discount": 553.00,
    "final_price": 272.00
}
###

PUT http://localhost:3000/orders/1
Content-Type: application/json

{
  "restaurant_id": 19,
    "delivery_address_id": 21,
    "user_id": 8,
    "driver_id": 5,
    "price": 873.00,
    "discount": 553.00,
    "final_price": 272.00
}
###

DELETE http://localhost:3000/orders/12