GET http://localhost:3000/restaurant_owner
###

GET http://localhost:3000/restaurant_owner?limit=2
###

GET http://localhost:3000/restaurant_owner/13
###

POST http://localhost:3000/restaurant_owner/create
Content-Type: application/json

{
    "restaurant_id": 13,
    "owner_id": 9
}
###

PUT http://localhost:3000/restaurant_owner/1
Content-Type: application/json

{
    "restaurant_id": 12,
    "owner_id": 9
}

###
DELETE http://localhost:3000/restaurant_owner/12