POST  http://localhost:3000/auth/sign_up
Content-Type: application/json

{
    "user_id":2,
    "username": "Zoey",
    "password": "pass",
    "role": "admin"
}

###
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "Zoey",
    "password": "pass"
}
