POST  http://localhost:3000/auth/sign_up
Content-Type: application/json

{
    "name": "Hunter filly",
    "contact_phone": "1234567890",
    "username": "hunter",
    "phone_verified": false,
    "email": "zoeyfilly@yahoo.com",
    "email_verified": false,
    "confirmation_code": "123456",
    "password": "pass"

}

###
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "Zoey",
    "password": "pass"
}

###
PUT http://localhost:3000/auth/updaterole/2
Content-Type: application/json

{
    "username": "Silas" ,
    "password": "Ysi8sxDxOI9tu1v",
    "role": "user"
}
